### ISSUE TITLE
`{{with}}` deprecation from ember-basic-dropdown v3

### ISSUE THREAD

**Issue by gorner** [mydea/ember-date-components#272]
This add-on currently depends on ember-basic-dropdown (EBD) v3, which [uses](https://github.com/cibernox/ember-basic-dropdown/blob/v3.1.0/addon/templates/components/basic-dropdown.hbs#L1) the `{{with}}` helper which is [deprecated](https://deprecations.emberjs.com/v3.x/#toc_ember-glimmer-with-syntax) (and raises a build-time warning) in Ember v3.26+ and removed in Ember v4.0.

Currently working in an app (which we are slowly working towards upgrading to Ember v4) that directly depends on EBD v6 for other reasons and this package doesn't seem to conflict with it (apart from still raising the warning). Would be willing to submit a PR to update to ember-basic-dropdown v6 (which supports Ember v3.28+), or alternatively allow this package to accept a range of acceptable versions of EBD.

**Comment by gorner** [comment]
I looked into this update this weekend and discovered a bunch of other updates that seemed to be required to ensure compatibility with newer versions of Ember. With that caveat, I got most things working, except for the Embroider runs of ember-try, which gave me a lot of errors along the lines of `TypeError: _externals_moment__WEBPACK_IMPORTED_MODULE_1__.isMoment is not a function` which didn't work even if I tried things like `import { isMoment } from 'moment'`. Apart from that attempt, however, I didn't need to touch any of the add-on code itself.

If anyone's curious, this is my working branch: https://github.com/gorner/ember-date-components/tree/update-ember-basic-dropdown-v6

For now, for the app I'm working on, I've realized it'll probably be sufficient to just specify ember-basic-dropdown v6 in npm overrides (or equivalently yarn resolutions).

Edit: I've tried a couple of other things since then (including moving Moment to dependencies) to no avail. But on review, it looks like the current release may not work with Embroider either? Perhaps I will just go ahead and create the PR.

**Comment by gorner** [comment]
> For now, for the app I'm working on, I've realized it'll probably be sufficient to just specify ember-basic-dropdown v6 in npm overrides (or equivalently yarn resolutions).

Just a heads-up for anyone else using this workaround, it also worked with EBD v7 but does not work with EBD v8+ due to its [conversion](https://ember-basic-dropdown.com/docs/migrate-7-0-to-8-0/) to the v2 addon format:

```
Error: ember-date-components needs to depend on ember-auto-import in order to use ember-basic-dropdown
    at Class.registerV2Addon (<app_path>/node_modules/@embroider/addon-shim/src/index.js:122:27)
    at Class.included (<app_path>/node_modules/@embroider/addon-shim/src/index.js:42:18)
    at Class.superWrapper [as included] (<app_path>/node_modules/core-object/lib/assign-properties.js:34:20)
    at <app_path>/node_modules/ember-cli/lib/models/addon.js:497:26
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (<app_path>/node_modules/ember-cli/lib/models/addon.js:494:24)
    at Class.included (<app_path>/node_modules/ember-cli/lib/models/addon.js:769:10)
    at Class.superWrapper [as included] (<app_path>/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class.included (<app_path>/node_modules/ember-date-components/index.js:9:26)
    at Class.superWrapper [as included] (<app_path>/node_modules/core-object/lib/assign-properties.js:34:20)
    at <app_path>/node_modules/ember-cli/lib/broccoli/ember-app.js:653:15
    at Array.forEach (<anonymous>)
    at EmberApp._notifyAddonIncluded (<app_path>/node_modules/ember-cli/lib/broccoli/ember-app.js:651:25)
    at new EmberApp (<app_path>/node_modules/ember-cli/lib/broccoli/ember-app.js:137:10)
    at module.exports (<app_path>/ember-cli-build.js:60:13)
    at Builder.readBuildFile (<app_path>/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (<app_path>/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (<app_path>/node_modules/ember-cli/lib/models/builder.js:29:10)
    at ServeTask.run (<app_path>/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at <app_path>/node_modules/ember-cli/lib/models/command.js:238:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Class.run (<app_path>/node_modules/ember-cli/lib/commands/serve.js:106:5)
```

**Comment by gorner** [comment]
@mydea The app I'm working on is currently blocked on some updates, including the aforementioned ember-basic-dropdown v8, due to the issues mentioned [previously](https://github.com/mydea/ember-date-components/issues/272#issuecomment-2018800388). Do you have any near-term plans to bring this addon up to date (or accept PRs to do so)? 

If not, I'm considering publishing a fork with the necessary updates (possibly slimmed down to just the time-picker as we use ember-power-calendar for dates).

**Comment by gorner** [comment]
I've gone ahead and published a fork, `@gorner/ember-date-components` ([NPM](https://www.npmjs.com/package/@gorner/ember-date-components), [GitHub](https://github.com/gorner/ember-date-components)). I've left it intact for now but I may still carve out the time-picker pieces into a separate package in the near future.

If the original repo is brought up-to-date I would be happy to deprecate the fork and point back to the original.
